query Page($slug: String!, $stage: Stage! = PUBLISHED, $locale: Locale!) {
  page(locales: [$locale], where: { slug: $slug }, stage: $stage) {
    __typename
    id
    slug
    title
    description
    ogImage(locales: [$locale, en]) {
      url
    }
    components {
      ... on Editorial {
        id
        __typename
        image(locales: [$locale, en]) {
          url
        }
        components {
          ... on Card {
            id
            __typename
            cta
            image(locales: [$locale, en]) {
              url
            }
            title
            url
          }
          ... on Cta {
            id
            __typename
            chapeau
            cta
            description
            title
            url
          }
        }
      }
      ... on Hero {
        id
        __typename
        description
        image(locales: [$locale, en]) {
          url
        }
        title
      }
      ... on ProductHighlight {
        id
        __typename
        productFocus {
          id
          __typename
          cta
          description
          image(locales: [$locale, en]) {
            url
          }
          productId
          title
          url
          product {
            description
            id
            images {
              alt
              url
            }
            ingredients
            price
            name
            shortDescription
            slug
            stock
          }
        }
      }
      ... on Routine {
        id
        __typename
        chapeau
        cta
        description
        image(locales: [$locale, en]) {
          url
        }
        title
        url
      }
    }
  }
}
