query Pdp($slug: String!, $stage: Stage! = PUBLISHED, $locale: Locale!) {
  pdp(locales: [$locale], where: { slug: $slug }, stage: $stage) {
    id
    __typename
    slug
    title
    description
    ogImage(locales: [$locale, en]) {
      url
    }
    components {
      ... on Tutorial {
        __typename
        id
        title
        image(locales: [$locale, en]) {
          url
        }
        items {
          __typename
          text
        }
      }
      ... on Routine {
        __typename
        id
        chapeau
        cta
        description
        image(locales: [$locale, en]) {
          url
        }
        title
        url
      }
      ... on ProductList {
        __typename
        title
        relatedProductList {
          relatedProductId
          relatedProducts {
            products {
              description
              id
              images {
                alt
                url
              }
              ingredients
              name
              price
              shortDescription
              slug
              stock
            }
          }
        }
      }
    }

    commercetoolsProduct {
      id
      masterData {
        current {
          slug(locale: "en-GB")
          metaTitle(locale: "en-GB")
          metaDescription(locale: "en-GB")
          name(locale: "en-GB")
          description(locale: "en-GB")
          categories {
            name(locale: "en-GB")
          }
          allVariants {
            id
            attributesRaw {
              name
              value
            }
            images {
              url
              label
            }
            price(currency: "EUR") {
              value {
                type
                currencyCode
                centAmount
                fractionDigits
              }
            }
            sku
          }
        }
      }
    }

    reviews {
      data {
        comment
        id
        name
        product
        productSlug
        rating
      }
    }
  }
}
